version: 2

sphinx:
  configuration: docs/source/conf.py

formats: all

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
    nodejs: "18"
  jobs:
    post_create_environment:
      - pip install poetry
      - poetry config virtualenvs.create false
    pre_install:
      - npm install
      - npm run build
    post_install:
      - poetry install
