version: 2

sphinx:
  configuration: docs/source/conf.py

formats: all

build:
  os: ubuntu-24.04
  tools:
    python: "3.11"
    nodejs: "18"
  jobs:
    post_create_environment:
      - pip install uv
    pre_install:
      - npm install
      - npm run build
    post_install:
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH uv sync --active
