version: 2

sphinx:
  configuration: docs/source/conf.py

formats: all

python:
  install:
    - method: pip
      path: .

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
    nodejs: "18"
  jobs:
    pre_install:
      - npm install
      - npm run build
